#doctrine:
#    orm:
#        entity_managers:
#            default:
#                mappings:
#                    FOSUserBundle: ~
#                    ApplicationSonataUserBundle: ~
#                    SonataUserBundle: ~

sonata_user:
    security_acl: false
    manager_type: orm